# Generated by Django 5.2 on 2025-04-19 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kvitsapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='apraksts',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='cena',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='ean13',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sku',
        ),
        migrations.AddField(
            model_name='product',
            name='attels',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='pasutijuma_kods',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
